[theme]
primaryColor = "#FF4B4B"         # å¼·èª¿è‰²ï¼ˆãƒœã‚¿ãƒ³ã‚„ãƒªãƒ³ã‚¯ï¼‰
backgroundColor = "#000000"      # èƒŒæ™¯è‰²ï¼ˆé»’ï¼‰
secondaryBackgroundColor = "#1c1c1c"  # ã‚µã‚¤ãƒ‰ãƒãƒ¼ãªã©ã®èƒŒæ™¯
textColor = "#FFFFFF"            # ãƒ†ã‚­ã‚¹ãƒˆè‰²
font = "sans serif"              # ãƒ•ã‚©ãƒ³ãƒˆï¼ˆserif / sans serif / monospaceï¼‰

[server]
headless = true
port = 8501
enableCORS = false

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[general]
pageTitle = "æœ€å°åˆ†æ•£ãƒ•ãƒ­ãƒ³ãƒ†ã‚£ã‚¢ã®è¨ˆç®—"   # ã‚¿ãƒ–ã«è¡¨ç¤ºã•ã‚Œã‚‹ã‚¿ã‚¤ãƒˆãƒ«
favicon = "ğŸ“ˆ"                         # ãƒ–ãƒ©ã‚¦ã‚¶ã‚¿ãƒ–ã®ã‚¢ã‚¤ã‚³ãƒ³ï¼ˆçµµæ–‡å­— or ç”»åƒãƒ‘ã‚¹ï¼‰
